CREATE DATABASE BANCO;
USE BANCO;

CREATE TABLE LOGIN (
  EMAIL VARCHAR(100),
  SENHA VARCHAR (100),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
	
CREATE TABLE ATIVIDADE(
	ID_ATIVIDADE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(15) UNIQUE NOT NULL,
    STATS TINYINT (1) DEFAULT (0),
    DATA_PREVISTA DATE,
	CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Lista todos os Itens da Tabela
SELECT * FROM ATIVIDADE;

INSERT INTO LOGIN (email,senha) VALUES ('adm@gmail', '123');

-- Método de busca
SELECT * FROM LOJAS 
WHERE USUARIO LIKE '%João%';

-- Atualizar dados
UPDATE LOJAS 
SET EMAIL = 'novoemail@gmail.com' , TELEFONE = '7188888'
WHERE ID =1;

-- Deletar algum registro
DELETE FROM LOJAS
WHERE ID =2;